### ISSUE TITLE
Ajout d'espèces dans l'ajout d'une visite sans passer par TaxHub

### ISSUE THREAD

**Issue by jolleon** [jolleon/GeoNature-citizen#28]

**Comment by QuentinJouet** [comment]
Pour l'étape 6/7 : "Faune et flore" où l'on pourra renseigner les espèces observées sur la mare,  voici ce que l'on propose/souhaite. 

Je n'ai pas encore le petit texte à intégrer qui mentionne iNaturaliste et Faune Isère... Je vous envoie ça lundi. 

Vertébrés
Amphibiens indéterminés
Grenouilles
Crapauds
Tritons
Têtards
Pontes d’amphibiens en "chapelet"
Pontes d’amphibiens en "amas globulaire"
Poissons
Serpents
Oiseaux d’eau (canard, foulque, héron...)
Autres oiseaux (rouge-gorge, troglodyte, rapace...)
Ragondins / rats musqués
Mammifères indéterminés 

Invertébrés
Libellules (insecte posé : ailes ouvertes)
Lestes (insecte posé : ailes mi-ouvertes)
Demoiselles (insecte posé : ailes fermées)
Insectes aquatiques (dytiques, larves de libellules..)
Écrevisses

Plantes
Algues
Plantes aquatiques immergées 
Plantes aquatiques de berges 
(Pour les plantes, je sais qu'on a mis le taux de recouvrement sur l'étape "Berges et végétation" mais je ne pense pas que ce soit redondant car ils ne rempliront pas forcément toujours les deux...)

Autres précisons
"?" Vous pouvez renseigner ici le nom complet des espèces que vous avez identifié. C'est également ici que vous pouvez indiquer si des animaux autres que ceux proposés dans la liste étaient présents. 
Mettre un cadre de texte libre
