### ISSUE TITLE
La chasse aux papillons

### ISSUE THREAD

**Issue by jolleon** [jolleon/GeoNature-citizen#40]
Il y a encore des images de papillons hard-codées à certains endroit où il faudrait utiliser les vraies photos venant du backend pour les mares:

- [x] Liste des mares
- [x] popup mare sur la carte

(il y en a peut-être d'autres)

**Comment by lpofredc** [comment]
Le choix qui a été fait pour GeoNature citizen, une photo générique en cas d'absence de photo, sinon, la photo transmise.
