### ISSUE TITLE
Utiliser routeur ng pour lien details sur la popup

### ISSUE THREAD

**Issue by jolleon** [jolleon/GeoNature-citizen#41]
Le lien details de la popup mare sur la carte est un lien en dur

**Comment by jolleon** [comment]
En fait c'est compliqué à régler... https://stackoverflow.com/questions/43460579/angular-2-leaflet-map-how-to-link-to-a-component-from-marker-popup-rout

**Comment by QuentinJouet** [comment]
Voir éventuellement https://github.com/Asymmetrik/ngx-leaflet/issues/178
