### ISSUE TITLE
Login position

### ISSUE THREAD

**Issue by lpofredc** [jolleon/GeoNature-citizen#62]
Les fonctions de login / fiche utilisateur se superposent aux boutons de la carte.

![Sélection_287](https://user-images.githubusercontent.com/22891423/59306685-1d400600-8c9d-11e9-91e9-777bb0c5d823.png)

**Comment by jolleon** [comment]
C'est réglé dans https://github.com/jolleon/GeoNature-citizen/pull/68, j'ai bougé les contrôles de la carte sur la gauche (déplacer le login est plus compliqué vu que ça fait partie de la topbar).
