### ISSUE TITLE
Chargement de grosses photos

### ISSUE THREAD

**Issue by lpofredc** [jolleon/GeoNature-citizen#63]
Les grosses photos (fichiers de 3-4Mo) ne sont pas chargées. A creuser.

**Comment by QuentinJouet** [comment]
C'est une question de configuration du serveur http en production (timeout, max size, etc.)
En local, aucun problème à charger une photo de 5Mo.

**Comment by jolleon** [comment]
C'est effectivement principalement des réglages sur le serveur http pour améliorer ça (mettre un timeout des requetes plus long...).
Eventuellement dans le futur le frontend pourrait automatiquement redimensionner les photos trop grosses, mais ça ne me paraît pas être une priorité ou être nécessaire pour le projet mares.
